# Generated by Django 3.2.5 on 2021-07-24 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slotId', models.CharField(max_length=1000)),
                ('patientName', models.CharField(max_length=100)),
                ('bearerName', models.CharField(max_length=100)),
                ('patientAge', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('bookingTime', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isCancelled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['bookingTime'],
            },
        ),
    ]
