# Generated by Django 3.2.5 on 2021-07-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_auto_20210725_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slots',
            options={'ordering': ['startTime']},
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='isCancelled',
        ),
    ]
