# Generated by Django 3.2.5 on 2021-07-26 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slots', '0004_auto_20210725_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ['-bookingTime']},
        ),
        migrations.AddField(
            model_name='bookings',
            name='bookedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookings',
            name='slotName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='slotTime',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
